config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  root 'users#dashboard'

  get 'admin_dashboard', to: 'admins#dashboard'
  get 'teacher_dashboard', to: 'teachers#dashboard'

  resources :student_details


  resources :users, only: [] do
    collection do
      get :home
    end
    member do
      patch :update_role
    end
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def dashboard
    @student_details = StudentDetail.page(params[:page]).per(10)
  end

end

app/views/teachers/dashboard.html.erb
<div class="container">
  <table class="student-table">
    <thead>
    <tr>
      <th>Sl.No</th>
      <th>Name</th>
      <th>Subject</th>
      <th>Mark</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% current_page = params[:page].present? ? params[:page].to_i : 1 %>
    <% @student_details.each_with_index do |student, index| %>
      <tr>
        <td><%= (current_page - 1) * @student_details.limit_value + index + 1 %></td>
        <td>
          <span class="student-icon"><%= student.name[0].upcase %></span>
          <%= student.name %>
        </td>
        <td><%= student.subject %></td>
        <td><%= student.mark %></td>
        <td>
          <div class="dropdown">
            <button class="dropbtn">•••</button>
            <div class="dropdown-content">
              <%= link_to 'Edit', edit_student_detail_path(student, page: params[:page]), remote: true, class: 'edit-link'%>
              <%= link_to 'Delete', student_detail_path(student, page: params[:page]),
                          method: :delete,
                          data: { confirm: 'Are you sure you want to delete this student detail?' } %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="add-pagination">
    <button id="openModalBtn" class="add-button">+</button>

  <div class="pagination">
    <%= paginate @student_details %>
  </div>
  </div>


  <div id="addStudentModal" class="modal">
    <div class="modal-content">
      <span class="close">&times;</span>
      <h2>Add Student</h2>
      <%= form_with(model: StudentDetail.new, id: 'newStudentForm') do |form| %>
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, required: true %>
        </div>

        <%= hidden_field_tag :page, params[:page] %>

        <div class="form-group">
          <%= form.label :subject %>
          <%= form.text_field :subject, required: true %>
        </div>

        <div class="form-group">
          <%= form.label :mark %>
          <%= form.number_field :mark, required: true, min: 0 %>
        </div>

        <%= form.submit 'Add', class: 'add-button' %>
      <% end %>
    </div>
  </div>

  <div id="editStudentModal" class="modal">
    <div class="modal-content" id="editStudentModalContent">
    </div>
  </div>
</div>